server:
  port: 8080   # app runs at localhost:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sms_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: sms_user
    password: sms_pass_123

  jpa:
    hibernate:
      ddl-auto: update   # auto create/update tables from entities (dev only!)
    show-sql: true       # show SQL queries in console
    properties:
      hibernate.format_sql: true

  thymeleaf:
    cache: false

logging:
  level:
    org.springframework: INFO
