name: Test Student Management
on:
  workflow_dispatch
jobs:
  build:
   runs-on: self-hosted
   steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4
    # Step 2: Set up Java (use your version)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    # Step 3: Build with Maven
    - name: Build with Maven
      shell: cmd
      run: mvn -B clean package
        # Step 5: Start the Spring Boot app
    - name: Start Spring Boot app
      run: |
        nohup java -jar target/*.jar &
        sleep 10
        curl -I http://localhost:8080 || true

      
